jobs:
  Audits:
    secrets:
      GH_TOKEN: ${{ secrets.GH_OAUTH }}
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17
      maven-flags: -Daudits
name: Audits
on:
  repository_dispatch:
    types: trigger-ga___audits.yml
