jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    with:
      java: 17
name: Pull Requests
on:
  repository_dispatch:
    types: trigger-ga___pull-request.yml
